const Data = [
  {
    id: 1,
    symbol: require('../images/teslasymbol.jpg'),
    model: 'Model S',
    year: 2020,
    img: require('../images/t1.jpg'),
    status: 'Available',
    detailimg: require('../images/model_s.jpg'),
    subhead: 'Electric',
    driver: 'Surya Bhai',
    company: 'Tesla',
    phonenumber: 8523698741,
    garagestatus: true,
    owner: 'darshil bhai',
    carnumber: 'GJ05GL0001',
    insurance: new Date('2015-03-01'),
    puc: new Date('2015-03-01'),
    companyUse:true,
  },
  {
    id: 2,
    symbol: require('../images/teslasymbol.jpg'),
    model: 'Model x',
    year: 2021,
    img: require('../images/t2.jpg'),
    status: 'Unavailable',
    detailimg: require('../images/model_x.jpg'),
    subhead: 'Electric',
    driver: 'jadu Bhai',
    company: 'Tesla',
    phonenumber: 8523698741,
    owner: 'dhruval bhai',
    carnumber: 'GJ05GL0001',
    insurance: new Date('2015-03-25'),
    puc: new Date('2015-03-01'),
    companyUse:false,
  },
  {
    id: 3,
    symbol: require('../images/images.jpg'),
    model: 'M8',
    year: 2021,
    img: require('../images/bm1-removebg-preview.jpg'),
    status: 'Unavailable',
    detailimg: require('../images/Bmw_m8.jpg'),
    subhead: 'diesal',
    driver: 'jignesh Bhai',
    company: 'Bmw',
    phonenumber: 8523698741,
    garagestatus: true,
    owner: 'Rahul bhai',
    carnumber: 'GJ05GL0001',
    insurance: new Date('2015-03-25'),
    puc: new Date('2015-03-01'),
    companyUse:true,
  },
  {
    id: 4,
    symbol: require('../images/images.jpg'),
    model: 'X5',
    year: 2021,
    img: require('../images/bm3-removebg-preview.jpg'),
    status: 'Available',
    detailimg: require('../images/bmw_x5.jpg'),
    subhead: 'diesal',
    driver: 'chandu Bhai',
    company: 'Bmw',
    phonenumber: 8523698741,
    owner: 'Rakeshbhai bhai',
    carnumber: 'GJ05GL0001',
    insurance: new Date('2015-03-19'),
    puc: new Date('2015-03-01'),
    companyUse:true,
  },
  {
    id: 5,
    symbol: require('../images/Rolls-Royce-logo-2048x2048.jpg'),
    model: 'Ghost',
    year: 2020,
    img: require('../images/roll1-removebg-preview.jpg'),
    status: 'Available',
    detailimg: require('../images/rolls_ghost.jpg'),
    subhead: 'petrol',
    driver: 'xyz Bhai',
    company: 'Rolls Royce',
    phonenumber: 8523698741,
    garagestatus: true,
    owner: 'Nagjibhai bhai',
    carnumber: 'GJ05GL0001',
    insurance: new Date('2015-03-25'),
    puc: new Date('2015-03-01'),
    companyUse:true,
  },
  {
    id: 6,
    symbol: require('../images/Rolls-Royce-logo-2048x2048.jpg'),
    model: 'Phantom',
    year: 2021,
    img: require('../images/roll2-removebg-preview.jpg'),
    status: 'Unavailable',
    detailimg: require('../images/rolls_phantom.jpg'),
    subhead: 'diesal',
    driver: 'abc Bhai',
    company: 'Rolls Royce',
    phonenumber: 8523698741,
    owner: 'Arjan bhai',
    carnumber: 'GJ05GL0001',
    insurance: new Date('2015-03-20'),
    puc: new Date('2015-03-01'),
    companyUse:true,
  },
];
export default Data;